title: Jacob + Kristina = ❤️
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
atom_feed:
  hide: true

remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin    : "dirt" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"